### ISSUE TITLE
自动添加默认选中地址

### ISSUE THREAD

**Issue by duetg** [ytzong/UserScripts#1]
目前脚本会自动添加网页默认选中的达拉斯，而不会重复刷新。已经被扣掉几美分了。

**Comment by sssir** [comment]
不会重复刷新

**Comment by PetersonLian** [comment]
我能弱弱地问一下，大神，这个UserScripts项目干什么用的？翻墙用？ @duetg

**Comment by duetg** [comment]
用来刷Linode东京服务器的，买来以后想干嘛就干嘛了。 @PetersonLian

**Comment by PetersonLian** [comment]
我很好奇91porn-html5-player.user.js这是想干嘛

**Comment by PetersonLian** [comment]
@duetg 
现在linode下面可选的location里头，没有value==8的了，现在倒是有个tokyo2 JP,value值是11

**Comment by PetersonLian** [comment]
能给我个优惠码吗

**Comment by duetg** [comment]
@PetersonLian 我也没有码啊！每个月10刀。
